### PR TITLE
Owner upload

### PR DESCRIPTION
**Pull request by nkoenig**
# 🎉 New feature

## Summary
Support specification of owner during model upload.

## Test it

Example usage:
```
ign fuel upload --header "Private-Token: PRIVATE_TOKEN" -u "https://staging-fuel.ignitionrobotics.org" -o ORGANIZATION_NAME -m PATH_TO_MODEL
```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by iche033** [comment]
looks like adding an overloaded `UploadModel` function introduced an [ABI compatibility issue](https://build.osrfoundation.org/job/ignition_fuel-tools-abichecker-any_to_any-ubuntu_auto-amd64/289/API_5fABI_20report/)

**Comment by chapulina** [comment]
I think the ABI issue was spurious, the latest build passed

**Review by chapulina — APPROVED** [review]
Works for me! It would be nice to add a test, but I'm not sure how feasible that would be, so I'm ok without one for now.

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-10/1228/1

**Pull request merged**
