### PR TITLE
Bumps in garden: use ign-common5

### PR DESCRIPTION
**Pull request by chapulina**
See https://github.com/ignition-tooling/release-tools/issues/574

### CODE REVIEW

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
some console output from one of the windows test failures, not sure if it's relevant:

~~~
[ RUN      ] FuelClientTest.CachedModel
5: [Dbg] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc:48] Creating local model in [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8]
5: [Wrn] [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\LocalCache.cc:105] Server directory does not exist [C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\build\ignition-fuel_tools8\test_cache\fuel.ignitionrobotics.org]
5: C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(621): error: Value of: result
5:   Actual: false
5: Expected: true
~~~

**Comment by chapulina** [comment]
I opened a separate PR targeting Citadel with the test updates from 8fe711d:

* https://github.com/ignitionrobotics/ign-fuel-tools/pull/225

**Comment by chapulina** [comment]
> some console output from one of the windows test failures, not sure if it's relevant:

Thanks, I was looking for the error code in the test below:

```
5: [mC:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(621): error: Value of: result
5:   Actual: false
5: Expected: true
5: C:\Jenkins\workspace\ign_fuel-tools-pr-win\ws\ign-fuel-tools\src\FuelClient_TEST.cc(622): error: Expected equality of these values:
5:   ResultType::FETCH_ALREADY_EXISTS
5:     Which is: 4-byte object <05-00 00-00>
5:   result.Type()
5:     Which is: 4-byte object <07-00 00-00>
```

It's getting a `FETCH_ERROR`, I'll track where that can be coming from

**Comment by chapulina** [comment]
I think it's the colon on the directory paths (https://github.com/ignitionrobotics/ign-fuel-tools/issues/204). Someone needs dig into this and solve it for all versions. There are inconsistencies on how fuel-tools and common handle this for different versions :confused:

**Comment by chapulina** [comment]
Ok, so Windows has test failures on Edifice and Fortress, and the Windows check is not required on those branches. I think we should also remove the requirement for Garden, merge this, and when https://github.com/ignitionrobotics/ign-fuel-tools/issues/106 is fixed for Edifice, the fix should be forward-ported and CI cleaned up.

What do you think, @scpeters ?

**Comment by chapulina** [comment]
I removed the requirement for Windows CI on `main` and updated 

* https://github.com/ignition-tooling/release-tools/issues/398.

I think this is ready!

**Review by scpeters — APPROVED** [review]

**Comment by chapulina** [comment]
Merging this and its infrastructure PRs:

* https://github.com/ignition-release/ign-fuel-tools8-release/pull/2
* https://github.com/osrf/homebrew-simulation/pull/1761
* https://github.com/ignition-tooling/gazebodistro/pull/69

**Pull request merged**
