### PR TITLE
5 ➡️ 6 

### PR DESCRIPTION
**Pull request by mjcarroll**
# ➡️ Forward port

Port ign-fuel-tools5 to ign-fuel-tools6

Branch comparison: https://github.com/ignitionrobotics/ign-fuel-tools/compare/ign-fuel-tools6...ign-fuel-tools5

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
LGTM with happy CI

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by scpeters** [comment]
new windows test failure:

~~~
C:\Jenkins\workspace\ignition_fuel-tools-ci-pr_any-windows7-amd64\ws\ign-fuel-tools\src\Helpers_TEST.cc:36
Expected equality of these values:
  common::joinPaths("localhost:8000", "some", "path")
    Which is: "localhost8000\\some\\path"
  uriToPath(uri)
    Which is: "localhost:8000\\some\\path"
~~~

**Comment by chapulina** [comment]
> new windows test failure:

I see this failing on `ign-fuel-tools6`: 

https://build.osrfoundation.org/job/ign_fuel-tools-ign-6-win/2/testReport/junit/(root)/HelpersTEST/UriToPathNoAuthority/

I believe it's caused by some change upstream on `ign-common`.

I'm going to merge this PR since it didn't introduce the only test failure, and it fixes some of the test failures currently in `ign-fuel-tools6`/

**Pull request merged**
