### PR TITLE
Bumps in garden : ign-fuel-tools8

### PR DESCRIPTION
**Pull request by methylDragon**
See https://github.com/ignition-tooling/release-tools/issues/685

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by methylDragon** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
No new failures, merging!

**Pull request merged**
