### PR TITLE
Bumps in garden : ci_matching_branch/bump_garden_ign-fuel-tools8

### PR DESCRIPTION
**Pull request by scpeters**
See https://github.com/ignition-tooling/release-tools/issues/554

### CODE REVIEW

**Comment by scpeters** [comment]
the homebrew CI build failed because the homebrew-simulation branch was out of date and didn't include https://github.com/osrf/homebrew-simulation/pull/1703. I've merged the branch with `master` and will restart the job

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-homebrew-amd64/661/) https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-homebrew-amd64/661/

🎉

**Comment by scpeters** [comment]
I manually opened https://github.com/ignition-tooling/gzdev/pull/42 with a matching branch name and restarted the Ubuntu jenkins job

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/680/) https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/680/

🎉

**Comment by scpeters** [comment]
I've merged https://github.com/ignition-tooling/gzdev/pull/42 and restarted the GitHub actions workflows

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
I've added the matching branch feature for windows in https://github.com/ignition-tooling/release-tools/pull/583

[Build Status](https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/101/) https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/101/

🎉

**Comment by scpeters** [comment]
I need to fix https://github.com/osrf/homebrew-simulation/pull/1704 before merging this

**Pull request merged**
