### PR TITLE
Hide Private headers and LocalCache.hh

### PR DESCRIPTION
**Pull request by ahcorde**
This PR is related with these issues: https://github.com/ignitionrobotics/ign-fuel-tools/issues/44 and https://github.com/ignitionrobotics/ign-fuel-tools/issues/29

Private headers and `LocalCache.hh` moved to the `src` folder.

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by scpeters** [comment]
I think we can remove the following exclusion in the include folder's CMakeLists.txt:

* https://github.com/ignitionrobotics/ign-fuel-tools/blob/master/include/ignition/fuel_tools/CMakeLists.txt#L3

**Comment by chapulina** [comment]
Just checking @scpeters and @nkoenig - your approvals mean you don't think a tick-tock cycle is needed? I could agree with that for the `Private` classes, but I really think we should tick-tock the `LocalCache`.

**Comment by scpeters** [comment]
> Just checking @scpeters and @nkoenig - your approvals mean you don't think a tick-tock cycle is needed? I could agree with that for the `Private` classes, but I really think we should tick-tock the `LocalCache`.

it was a lazy review on my part. I think tick-tocking is probably right for `LocalCache`, but since it's targeted at the next major version, I think the `Private` header files could just be removed

**Comment by ahcorde** [comment]
I'm fine doing this:

> * Dome: add `IGN_DEPRECATED` to all constructors and static functions of the classes to be removed
> * Ign-E: Move the headers to `src`

But I have a question @chapulina. Right now the [collection-dome.yaml](https://raw.githubusercontent.com/ignition-tooling/gazebodistro/master/collection-dome.yaml) is pointing to `master`, which means there is no difference right now between Dome and ign-E.
  - Should we wait until a tag for ign-fuel-tools in Dome (ign-fuel-tools5) is created ?
  - Which other way to proceed ?

**Comment by chapulina** [comment]
>  no difference right now between Dome and ign-E.

Yup, you're right. What we usually do is add the deprecations now, and once we branch `ign-fuel-tools5` off of `master`, we bump master's version and also remove the deprecated functions.

**Comment by ahcorde** [comment]
Deprecated LocalCache constructor. The other headers are moved to `src`

**Comment by chapulina** [comment]
Can you fix the conflicts, @ahcorde ? Then if CI is clear this LGTM.

**Comment by ahcorde** [comment]
Done @chapulina ;)

**Comment by chapulina** [comment]
We should suppress the deprecation warnings caused by `LocalCache`. [Here](https://github.com/ignitionrobotics/ign-gazebo/blob/5b65ca67d10aa64f992fb98fd3c160999f1b75f8/src/Conversions.cc#L573-L580)'s an example of how we usually do it.

**Comment by chapulina** [comment]
@osrf-jenkins run tests por favor

**Pull request merged**
