### PR TITLE
Move test cache to build folder

### PR DESCRIPTION
**Pull request by chapulina**
# 🦟 Bug fix

## Summary

While debugging a test failure, I noticed that the tests in `ign_src_TEST` would fail if run from outside the build directory. So I fixed this by passing `PROJECT_BINARY_PATH` to all the places where the `test_cache` is accessed. In order to reduce duplication, I moved that logic to the `SetUp` function. While at it, I reduced more duplication by moving the `IO` functions to `SetUp` / `TearDown`.

The fix can be checked by running the test from a directory other than `build`, for example:

`./build/ignition-fuel_tools5/bin/UNIT_ign_src_TEST`

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by mjcarroll** [comment]
We don't currently depend on `ign-common` here, but if we did, it would be even safer to utilize `TempDirectory` to guarantee that the cache is destroyed between runs of the test.

**Comment by mjcarroll** [comment]
Must have been thinking of a different library, we do actually depend on ign-common.

**Comment by chapulina** [comment]
> it would be even safer to utilize TempDirectory to guarantee that the cache is destroyed between runs of the test.

Good idea. We'd have to backport that to `ign-common3` though, this PR is targeting Citadel.

One thing to point out though is that the cache isn't deleted here between tests. That's helpful when debugging test failures so the user can inspect the cache after running a test. I don't think it's extremely necessary though.

**Comment by mjcarroll** [comment]
> One thing to point out though is that the cache isn't deleted here between tests. That's helpful when debugging test failures so the user can inspect the cache after running a test. I don't think it's extremely necessary though.

The `TempDirectory` class currently has a flag that will allow you to block the cleanup.  This is only exposed in code, but may be useful to also have as an environment variable?

**Comment by chapulina** [comment]
> The TempDirectory class currently has a flag that will allow you to block the cleanup. This is only exposed in code, but may be useful to also have as an environment variable?

Oh nice! An env var could be helpful, I personally don't mind adding a line while debugging to avoid cleanup though, good to know it's exposed through the API

**Review by mjcarroll — APPROVED** [review]

**Pull request merged**
